### Tarea2 - Juan de Dios Murillo Morera

In [1]:
import os
import pandas as pd
import numpy  as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix
from pandas import DataFrame
from keras.models import Sequential
from keras.layers import Activation, Dense
import keras.models
from matplotlib import colors as mcolors
import warnings
from sklearn.preprocessing import LabelEncoder
warnings.filterwarnings('ignore')
os.chdir("C:\\Users\\JUANMURILLOMORERA\\Desktop\\")

WARNING:tensorflow:From C:\Users\JUANMURILLOMORERA\PROMIDAT23\anaconda3\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [2]:
import AnalisisPredictivo as aP

In [3]:
import ModMC

### Ejercicio 1

In [4]:
#1.a
# 
df = pd.read_csv("potabilidad_V2.csv", delimiter=',' , decimal='.' , header=0, index_col=0)
df
df.shape
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2011 entries, 4 to 3272
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ph               2011 non-null   float64
 1   Hardness         2011 non-null   float64
 2   Solids           2011 non-null   float64
 3   Chloramines      2011 non-null   float64
 4   Sulfate          2011 non-null   float64
 5   Conductivity     2011 non-null   float64
 6   Organic_carbon   2011 non-null   float64
 7   Trihalomethanes  2011 non-null   float64
 8   Turbidity        2011 non-null   float64
 9   Potability       2011 non-null   object
dtypes: float64(9), object(1)
memory usage: 172.8+ KB

,ph,Hardness,Solids,Chloramines,Sulfate,Conductivity,Organic_carbon,Trihalomethanes,Turbidity,Potability
4,8.316766,214.373394,22018.417441,8.059332,356.886136,363.266516,18.436524,100.341674,4.628771,No
5,9.092223,181.101509,17978.986339,6.546600,310.135738,398.410813,11.558279,31.997993,4.075075,No
6,5.584087,188.313324,28748.687739,7.544869,326.678363,280.467916,8.399735,54.917862,2.559708,No
7,10.223862,248.071735,28749.716544,7.513408,393.663396,283.651634,13.789695,84.603556,2.672989,No
8,8.635849,203.361523,13672.091764,4.563009,303.309771,474.607645,12.363817,62.798309,4.401425,No

In [5]:
#1.b
datos=df
datos.loc[:, datos.columns != 'Potability'] = StandardScaler().fit_transform(datos.loc[:, datos.columns != 'Potability'])
datos

,ph,Hardness,Solids,Chloramines,Sulfate,Conductivity,Organic_carbon,Trihalomethanes,Turbidity,Potability
4,0.782466,0.564114,0.011687,0.583804,0.574378,-0.783962,1.227032,2.111652,0.844761,No
5,1.275463,-0.455653,-0.455835,-0.370947,-0.560480,-0.348429,-0.842154,-2.140399,0.135033,No
6,-0.954835,-0.234614,0.790645,0.259104,-0.158911,-1.810063,-1.792340,-0.714423,-1.807366,No
7,1.994902,1.596951,0.790764,0.239248,1.467140,-1.770608,-0.170876,1.132494,-1.662163,No
8,0.985323,0.226606,-0.954313,-1.622878,-0.726179,0.595858,-0.599824,-0.224135,0.553348,No
...,...,...,...,...,...,...,...,...,...,...
3268,1.210411,0.584770,-0.693978,-0.528284,-0.492625,-0.447578,-1.341281,-0.705001,0.825626,Si
3269,-0.243774,0.347964,-0.540564,0.362137,-0.697038,-1.205321,0.559422,-2.334474,-0.675183,Si
3270,2.800492,-3.100365,1.767503,1.343596,-1.803476,0.165656,0.546021,-1.545585,0.512125,Si
3271,-0.646160,-0.285317,0.488576,0.387023,0.302843,-0.131852,-0.688929,-0.372108,-0.384562,Si
3272,-1.537172,-0.070075,2.970287,0.020386,0.648718,1.238006,-0.139372,0.017846,0.597437,Si

In [6]:
nnet1 = MLPClassifier(hidden_layer_sizes = (5, 10, 10, 5) , max_iter = 50000, 
                     activation = "relu", solver = "adam", random_state = 0)
analisis_Potability = aP.AnalisisPredictivo(datos, predecir = "Potability", modelo = nnet1,
                                      train_size = 0.75, random_state = 0)
resultados = analisis_Potability.fit_predict_resultados()

Matriz de Confusión:
[[ 79 230]
 [ 89 105]]

Precisión Global:
0.3658051689860835

Error Global:
0.6341948310139165

Precisión por categoría:
         No        Si
0  0.255663  0.541237

In [7]:
nnet2 = MLPClassifier(hidden_layer_sizes = (5, 10, 10, 5), max_iter = 50000, 
                     activation = "tanh", solver = "adam", random_state = 0)
analisis_Potability = aP.AnalisisPredictivo(datos, predecir = "Potability", modelo = nnet2,
                                          train_size = 0.75, random_state = 0)
resultados = analisis_Potability.fit_predict_resultados()

Matriz de Confusión:
[[ 94 215]
 [106  88]]

Precisión Global:
0.36182902584493043

Error Global:
0.6381709741550696

Precisión por categoría:
         No        Si
0  0.304207  0.453608

In [16]:
nnet3 = MLPClassifier(hidden_layer_sizes = (5, 10, 10, 5), max_iter = 50000, 
                     activation = "tanh", solver = "lbfgs", random_state = 0)
analisis_Potability = aP.AnalisisPredictivo(datos, predecir = "Potability", modelo = nnet3,
                                          train_size = 0.75, random_state = 0)
resultados = analisis_Potability.fit_predict_resultados()

Matriz de Confusión:
[[108 201]
 [104  90]]

Precisión Global:
0.39363817097415504

Error Global:
0.606361829025845

Precisión por categoría:
         No        Si
0  0.349515  0.463918

In [12]:
from sklearn.preprocessing import LabelEncoder

#Dividimos los datos en variables predictoras y variable a predecir
X = np.array(datos.iloc[:, 0:9])
y = datos["Potability"].ravel()

#Recodificamos la variable a predecir a enteros de 0 a num_clases-1
encoder = LabelEncoder()
y = encoder.fit_transform(y)
x_train, x_test, y_train, y_test = train_test_split(X, y, train_size = 0.75, random_state = 0)

In [17]:
modelo = Sequential()
modelo.add(Dense(units = 5, activation = 'relu'))
modelo.add(Dense(units = 10, activation = 'relu'))
modelo.add(Dense(units = 10, activation = 'relu'))
modelo.add(Dense(units = 5, activation = 'relu'))
modelo.add(Dense(units = 1, activation = 'sigmoid'))
modelo.compile(
  optimizer = 'adam', loss = 'binary_crossentropy',
  metrics = 'accuracy')
  
modelo.fit(x_train, y_train, epochs = 100, batch_size = 16, verbose = 0)

In [18]:
pred = modelo.predict(x_test)

16/16 [==============================] - 0s 1ms/step

In [19]:
pred = [1 if p > 0.5 else 0 for p in pred]
pred = encoder.inverse_transform(pred)

# Recodificamos las etiquetas de y_test
y_test_classes = encoder.inverse_transform(y_test)

MC = confusion_matrix(y_test_classes, pred, labels = encoder.classes_)
indices = analisis_Potability.indices_general(MC, list(encoder.classes_))
for k in indices:
  print("\n%s:\n%s"%(k,str(indices[k])))

Matriz de Confusión:
[[224  85]
 [103  91]]

Precisión Global:
0.6262425447316103

Error Global:
0.37375745526838966

Precisión por categoría:
         No        Si
0  0.724919  0.469072

In [20]:
modelo = Sequential()
modelo.add(Dense(units = 5, activation = 'tanh'))
modelo.add(Dense(units = 10, activation = 'tanh'))
modelo.add(Dense(units = 10, activation = 'tanh'))
modelo.add(Dense(units = 5, activation = 'tanh'))
modelo.add(Dense(units = 1, activation = 'sigmoid'))
modelo.compile(
  optimizer = 'adam', loss = 'binary_crossentropy',
  metrics = 'accuracy')
  
modelo.fit(x_train, y_train, epochs = 100, batch_size = 16, verbose = 0)

In [21]:
pred = modelo.predict(x_test)

16/16 [==============================] - 0s 3ms/step

In [22]:
pred = [1 if p > 0.5 else 0 for p in pred]
pred = encoder.inverse_transform(pred)

# Recodificamos las etiquetas de y_test
y_test_classes = encoder.inverse_transform(y_test)

MC = confusion_matrix(y_test_classes, pred, labels = encoder.classes_)
indices = analisis_Potability.indices_general(MC, list(encoder.classes_))
for k in indices:
  print("\n%s:\n%s"%(k,str(indices[k])))

Matriz de Confusión:
[[223  86]
 [ 97  97]]

Precisión Global:
0.6361829025844931

Error Global:
0.36381709741550694

Precisión por categoría:
         No   Si
0  0.721683  0.5

In [23]:
 #1.c
 # Según los resultados obtenidos el estudio con mejor resultado fue el de activation "tanh" con la creación de modelo sequential, 
# obteniéndose Precisión Global: 0.6361829025844931 y un error global de: Error Global:0.36381709741550694, superando los experimentos 
# anteriores

### Ejercicio 2

In [70]:
#2.a
df = pd.read_csv("ZipDataTrainCod.csv", sep=';', decimal=",")
print(df.info())
# Se van a utilizar todos los parámetros excepto la etiqueta
X = df.loc[:, df.columns != "Numero"]
#Estandarizamos los datos
Xtrain = pd.DataFrame(StandardScaler().fit_transform(X), columns= X.columns)
# Devuelve los datos como un array
ytrain = df['Numero'].ravel()

# training set
X_train = Xtrain
y_train = ytrain

df = pd.read_csv("ZipDataTestCod.csv", sep=';', decimal=",")
# Se van a utilizar todos los parámetros
X = df.loc[:, df.columns != "Numero"]
mat = X
#Estandarizamos los datos
Xtest = pd.DataFrame(StandardScaler().fit_transform(X), columns= X.columns)
# Devuelve los datos como un array
ytest = df['Numero'].ravel()

# testing set
X_test = Xtest
y_test = ytest

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7291 entries, 0 to 7290
Columns: 257 entries, Numero to V257
dtypes: object(257)
memory usage: 14.3+ MB
None

In [71]:
# genera el modelo predictivo, las predicciones y mide la calidad del modelo.
instancia_MLP = MLPClassifier(hidden_layer_sizes= (250, 100, 50, 25) , max_iter = 50000, 
                     activation = "relu", solver = "adam", random_state = 0)
instancia_MLP.fit(X_train.values,y_train)
prediccion = instancia_MLP.predict(X_test.values)
# Trabaja las etiquetas
labels = ["cero","uno","dos","tres","cuatro","cinco","seis","siete","ocho","nueve"]
# genera la matriz de confusion
MC = confusion_matrix(y_test, prediccion, labels=labels)
indices = ModMC.indices_general(MC,labels)
for k in indices:
    print("\n%s:\n%s"%(k,str(indices[k])))

Matriz de Confusión:
[[350   0   2   0   3   0   2   0   1   1]
 [  0 254   1   1   3   1   3   0   1   0]
 [  2   0 184   2   1   2   1   2   4   0]
 [  1   0   3 148   1   9   0   1   2   1]
 [  1   2   5   0 181   1   1   2   2   5]
 [  2   0   1   5   0 146   0   0   4   2]
 [  1   0   4   0   2   1 161   0   1   0]
 [  0   0   1   0   4   0   0 137   1   4]
 [  3   0   2   4   3   2   0   1 150   1]
 [  0   1   0   0   0   0   0   2   2 172]]

Precisión Global:
0.9382162431489786

Error Global:
0.06178375685102144

Precisión por categoría:
      cero       uno       dos      tres  cuatro   cinco      seis     siete  \
0  0.97493  0.962121  0.929293  0.891566   0.905  0.9125  0.947059  0.931973

       ocho     nueve
0  0.903614  0.971751

In [75]:
#2.b
mat = X
def remplazaValor(x, valor):
    q = 64 # cantidad de interaciones 
    r = 4 # cantidad x bloque
    f = 2 # cantidad de filas
    b = 0
    y=0
    sum = 0.0
    for e in range(4):   
        y= y + b
        q=0
        while q<r:
            mat.iloc[x][y]=valor
            y=y+1
            q=q+1
        b=12

In [76]:
def reduccionProm(x):
    q = 64 # cantidad de interaciones
    r = 4 # cantidad x bloque
    b = 0
    sum = 0.0
    for w in range(16):
        y=0
        sum = 0.0
        for e in range(4):   
            y= y + b
            q=0
            while q<r:
                sum = sum + float(mat.iloc[x][y])
                y=y+1
                q=q+1
            b=12
        prom=sum/16
        remplazaValor(x, prom) 
for x in range(len(mat)):
    reduccionProm(x)

In [77]:
#Estandarizamos los datos
Xtest = pd.DataFrame(StandardScaler().fit_transform(X), columns= mat.columns)
# Devuelve los datos como un array
ytest = df['Numero'].ravel()
# testing set
X_test = Xtest
y_test = ytest

In [78]:
# genera el modelo predictivo, las predicciones y mide la calidad del modelo.
instancia_MLP = MLPClassifier(hidden_layer_sizes= (250, 100, 50, 25) , max_iter = 50000, 
                     activation = "relu", solver = "adam", random_state = 0)
instancia_MLP.fit(X_train.values,y_train)
prediccion = instancia_MLP.predict(X_test.values)
# Trabaja las etiquetas
labels = ["cero","uno","dos","tres","cuatro","cinco","seis","siete","ocho","nueve"]
# genera la matriz de confusion
MC = confusion_matrix(y_test, prediccion, labels=labels)
indices = ModMC.indices_general(MC,labels)
for k in indices:
    print("\n%s:\n%s"%(k,str(indices[k])))

Matriz de Confusión:
[[349   0   2   0   3   0   3   0   1   1]
 [  0 254   1   0   3   1   3   0   1   1]
 [  2   0 183   2   2   2   1   2   4   0]
 [  1   0   3 149   1   9   0   1   2   0]
 [  1   2   6   0 178   1   1   2   2   7]
 [  2   0   1   6   0 144   0   1   4   2]
 [  1   0   4   0   2   2 161   0   0   0]
 [  0   0   1   1   5   0   0 137   0   3]
 [  2   0   2   5   4   4   0   0 148   1]
 [  0   1   0   0   2   0   0   1   2 171]]

Precisión Global:
0.9337319382162431

Error Global:
0.06626806178375688

Precisión por categoría:
       cero       uno       dos     tres  cuatro  cinco      seis     siete  \
0  0.972145  0.962121  0.924242  0.89759    0.89    0.9  0.947059  0.931973

       ocho     nueve
0  0.891566  0.966102

In [80]:
def reduccionMay(x):
    q = 64 # cantidad de interaciones
    r = 4 # cantidad x bloque
    b = 0
    may = 0.0
    for w in range(16):
        y=0
        sum = 0.0
        for e in range(4):   
            y= y + b
            q=0
            while q<r:
                if float(mat.iloc[x][y])>may:
                    may = float(mat.iloc[x][y])
                y=y+1
                q=q+1
            b=12
        remplazaValor(x, may) 
for x in range(len(mat)):
    reduccionMay(x)

In [81]:
#Estandarizamos los datos
Xtest = pd.DataFrame(StandardScaler().fit_transform(X), columns= mat.columns)
# Devuelve los datos como un array
ytest = df['Numero'].ravel()
# testing set
X_test = Xtest
y_test = ytest

In [82]:
# genera el modelo predictivo, las predicciones y mide la calidad del modelo.
instancia_MLP = MLPClassifier(hidden_layer_sizes= (250, 100, 50, 25) , max_iter = 50000, 
                     activation = "relu", solver = "adam", random_state = 0)
instancia_MLP.fit(X_train.values,y_train)
prediccion = instancia_MLP.predict(X_test.values)
# Trabaja las etiquetas
labels = ["cero","uno","dos","tres","cuatro","cinco","seis","siete","ocho","nueve"]
# genera la matriz de confusion
MC = confusion_matrix(y_test, prediccion, labels=labels)
indices = ModMC.indices_general(MC,labels)
for k in indices:
    print("\n%s:\n%s"%(k,str(indices[k])))

Matriz de Confusión:
[[347   0   3   0   3   0   5   0   0   1]
 [  0 254   1   1   3   0   3   0   1   1]
 [  2   0 180   4   2   2   1   3   4   0]
 [  1   0   3 150   1   8   0   1   2   0]
 [  1   2   6   0 178   1   1   2   2   7]
 [  2   0   1   9   0 141   0   1   4   2]
 [  1   0   4   0   2   1 161   0   1   0]
 [  0   0   1   0   5   0   0 137   0   4]
 [  2   0   2   5   4   4   0   0 147   2]
 [  0   1   0   0   2   0   0   6   2 166]]

Precisión Global:
0.9272546088689586

Error Global:
0.07274539113104139

Precisión por categoría:
       cero       uno       dos      tres  cuatro    cinco      seis  \
0  0.966574  0.962121  0.909091  0.903614    0.89  0.88125  0.947059

      siete      ocho     nueve
0  0.931973  0.885542  0.937853

In [ ]:
# El resultado obtenido es muy interesante, ya que las tres versiones del algoritmo dan bastante bien en su resultado, se puede decir que 
# Lo que llama la atención es que a pesar de darse una reducción de la representación de los pixeles, no se está viendo afectado en el resultado final
# Por lo tanto, se sigue manteniendo con excelentes resultados apesar de la compresión de la información en lo que a sus pixeles y representación
# significa.

### Ejercicio 3

In [ ]:
# hecho a mano

### Ejercicio 4

In [103]:
import numpy  as np
class Perceptron():
    def __init__(self, W,C,X,Z): # Constructor
        self.__W = W
        self.__C = C
        self.__X = X
        self.__Z = Z
    @property
    def W(self):
        return self.__W
    @W.setter
    def W(self, p_W):
        self.__W = p_W
    @property
    def C(self):
        return self.__C
    @C.setter
    def C(self, p_C):
        self.__C = p_C       
    @property
    def X(self):
        return self.__X
    @X.setter
    def X(self, p_X):
        self.__X = p_X
    @property
    def Z(self):
        return self.__Z
    @Z.setter
    def Z(self, p_Z):
        self.__Z = p_Z     
    
    def FFuncion(self,i,w3,tc):
     sum = 0.0
     for j in range(3):
        sum = sum + ((w3[j]*self.__X[i][j])-self.__C[tc])
     return sum   
    def IFuncion(self,i,w3,tc):
        t = self.FFuncion(i,w3,tc)
        #t = (2 / (1+np.power(np.e,-t)))-1
        if t>=0:
           return 1
        else:
           return 0
    
    def EFuncion(self,w3,tc):
        sum = 0.0
        for i in range(4):
          sum = sum + (pow(self.IFuncion(i,w3,tc)-self.__Z[i],2))
          #print("primera iteracion",sum)
        return (sum/4)    
    def __str__(self):
        return f'Perceptron:'

W = [-1,-0.9,-0.8,-0.7,-0.6,-0.5,-0.4,-0.3,-0.2,-0.1,0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1]
C = [0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1]
X = [[1, 0, 0], 
      [1, 0, 1], 
      [1, 1, 0],
      [1, 1, 1]
     ]
Z = [0,1,1,0]
     
p = Perceptron(W,C,X,Z)

x=0
for tc in range(10):
  x=0  
  print('Valor de cita:', C[tc])
  for i in range(7):
     print(W[x:x+3], end="")
     print("Valor del error",p.EFuncion(W[x:x+3],tc))
     x = x+3

Valor de cita: 0
[-1, -0.9, -0.8]Valor del error 0.5
[-0.7, -0.6, -0.5]Valor del error 0.5
[-0.4, -0.3, -0.2]Valor del error 0.5
[-0.1, 0, 0.1]Valor del error 0.5
[0.2, 0.3, 0.4]Valor del error 0.5
[0.5, 0.6, 0.7]Valor del error 0.5
[0.8, 0.9, 1]Valor del error 0.5
Valor de cita: 0.1
[-1, -0.9, -0.8]Valor del error 0.5
[-0.7, -0.6, -0.5]Valor del error 0.5
[-0.4, -0.3, -0.2]Valor del error 0.5
[-0.1, 0, 0.1]Valor del error 0.5
[0.2, 0.3, 0.4]Valor del error 0.25
[0.5, 0.6, 0.7]Valor del error 0.5
[0.8, 0.9, 1]Valor del error 0.5
Valor de cita: 0.2
[-1, -0.9, -0.8]Valor del error 0.5
[-0.7, -0.6, -0.5]Valor del error 0.5
[-0.4, -0.3, -0.2]Valor del error 0.5
[-0.1, 0, 0.1]Valor del error 0.5
[0.2, 0.3, 0.4]Valor del error 0.5
[0.5, 0.6, 0.7]Valor del error 0.25
[0.8, 0.9, 1]Valor del error 0.5
Valor de cita: 0.3
[-1, -0.9, -0.8]Valor del error 0.5
[-0.7, -0.6, -0.5]Valor del error 0.5
[-0.4, -0.3, -0.2]Valor del error 0.5
[-0.1, 0, 0.1]Valor del error 0.5
[0.2, 0.3, 0.4]Valor del error 0.75
[0.5, 0.6, 0.7]Valor del error 0.25
[0.8, 0.9, 1]Valor del error 0.25
Valor de cita: 0.4
[-1, -0.9, -0.8]Valor del error 0.5
[-0.7, -0.6, -0.5]Valor del error 0.5
[-0.4, -0.3, -0.2]Valor del error 0.5
[-0.1, 0, 0.1]Valor del error 0.5
[0.2, 0.3, 0.4]Valor del error 0.5
[0.5, 0.6, 0.7]Valor del error 0.5
[0.8, 0.9, 1]Valor del error 0.25
Valor de cita: 0.5
[-1, -0.9, -0.8]Valor del error 0.5
[-0.7, -0.6, -0.5]Valor del error 0.5
[-0.4, -0.3, -0.2]Valor del error 0.5
[-0.1, 0, 0.1]Valor del error 0.5
[0.2, 0.3, 0.4]Valor del error 0.5
[0.5, 0.6, 0.7]Valor del error 0.75
[0.8, 0.9, 1]Valor del error 0.25
Valor de cita: 0.6
[-1, -0.9, -0.8]Valor del error 0.5
[-0.7, -0.6, -0.5]Valor del error 0.5
[-0.4, -0.3, -0.2]Valor del error 0.5
[-0.1, 0, 0.1]Valor del error 0.5
[0.2, 0.3, 0.4]Valor del error 0.5
[0.5, 0.6, 0.7]Valor del error 0.75
[0.8, 0.9, 1]Valor del error 0.5
Valor de cita: 0.7
[-1, -0.9, -0.8]Valor del error 0.5
[-0.7, -0.6, -0.5]Valor del error 0.5
[-0.4, -0.3, -0.2]Valor del error 0.5
[-0.1, 0, 0.1]Valor del error 0.5
[0.2, 0.3, 0.4]Valor del error 0.5
[0.5, 0.6, 0.7]Valor del error 0.5
[0.8, 0.9, 1]Valor del error 0.75
Valor de cita: 0.8
[-1, -0.9, -0.8]Valor del error 0.5
[-0.7, -0.6, -0.5]Valor del error 0.5
[-0.4, -0.3, -0.2]Valor del error 0.5
[-0.1, 0, 0.1]Valor del error 0.5
[0.2, 0.3, 0.4]Valor del error 0.5
[0.5, 0.6, 0.7]Valor del error 0.5
[0.8, 0.9, 1]Valor del error 0.75
Valor de cita: 0.9
[-1, -0.9, -0.8]Valor del error 0.5
[-0.7, -0.6, -0.5]Valor del error 0.5
[-0.4, -0.3, -0.2]Valor del error 0.5
[-0.1, 0, 0.1]Valor del error 0.5
[0.2, 0.3, 0.4]Valor del error 0.5
[0.5, 0.6, 0.7]Valor del error 0.5
[0.8, 0.9, 1]Valor del error 0.75

In [105]:
# Probar los valores

In [106]:
# Definimos la función H
def function_h(X, W, b):
    suma = 0
    mult = np.multiply(W,X)
    for a in mult:
        suma = suma + a
    suma = suma + b
    return suma

In [107]:
def s(x):
    r = np.power(np.e,-x)
    return (2 / (1+r))-1

In [113]:
entradas = np.array([0.8, 0.9, 1])
pesos = np.array([1,0,0])
sesgo = 0.3

# pase frontal
h = function_h(entradas, pesos, sesgo)
salida = s(h)
print(h)
print('salida: ', salida)

1.1
salida:  0.5005202111902354

In [114]:
entradas = np.array([0.8, 0.9, 1])
pesos = np.array([1,0,1])
sesgo = 0.3

# pase frontal
h = function_h(entradas, pesos, sesgo)
salida = s(h)
print(h)
print('salida: ', salida)

2.1
salida:  0.7818063576087741

In [115]:
entradas = np.array([0.8, 0.9, 1])
pesos = np.array([1,1,0])
sesgo = 0.3

# pase frontal
h = function_h(entradas, pesos, sesgo)
salida = s(h)
print(h)
print('salida: ', salida)

2.0
salida:  0.7615941559557646

In [116]:
entradas = np.array([0.8, 0.9, 1])
pesos = np.array([1,1,1])
sesgo = 0.3

# pase frontal
h = function_h(entradas, pesos, sesgo)
salida = s(h)
print(h)
print('salida: ', salida)

3.0
salida:  0.9051482536448663